export const ORDER_GETALL_REQUEST = "ORDER_GETALL_REQUEST";
export const ORDER_GETALL_SUCCESS = "ORDER_GETALL_SUCCESS";
export const ORDER_GETALL_FAIL = "ORDER_GETALL_FAIL";
export const ORDER_GETALL_RESET = "ORDER_GETALL_RESET";